config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_applications, only: [:index, :update, :destroy]
  resources :bulk_user_applications, only: [:create]

  root "user_applications#index"
end

app/models/application.rb
class Application < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :color, presence: true
  validates :default_status, presence: true, inclusion: { in: ["Yes", "No"] }
  validates :link, presence: true

  has_many :user_applications
  has_many :users, through: :user_applications

  # dynamic tailwind classes need to be added to the safelist in tailwind.config.js
  def background_class
    "bg-#{self.color.downcase}-300 hover:bg-#{self.color.downcase}-400"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable

  # custom validation instead of devise validatable, because we are using login instead of email
  validates :login, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { in: 6..128 }

  has_many :user_applications
  has_many :applications, through: :user_applications

  after_create :add_default_applications

  private
    def add_default_applications
      applications = Application.where(default_status: 'Yes').order(:id)

      applications.each do |application|
        self.user_applications.create(application: application)
      end

    end
end

app/models/user_application.rb
class UserApplication < ApplicationRecord
  default_scope { order(:position) }

  belongs_to :user
  belongs_to :application

  acts_as_list scope: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected
    def require_login
      unless user_signed_in?
        redirect_to new_user_session_path
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:login])
    end
end

app/controllers/bulk_user_applications_controller.rb
class BulkUserApplicationsController < ApplicationController
  before_action :require_login

  def create
    user = current_user
    application_ids = params[:application_ids].reject { |x| x.to_s.empty? }

    application_ids.each do |application_id|
      # verify application with id exists and isn't already related to the current_user
      if application = Application.find(application_id)
        if !user.user_applications.include?(application)
          user.user_applications.create(application: application)
        end
      end
    end
    redirect_to root_path
  end
end

app/controllers/user_applications_controller.rb
class UserApplicationsController < ApplicationController
  before_action :require_login

  def index
    user = current_user
    @user_applications = user.user_applications
    @available_applications = Application.where.not(id: UserApplication.where(user_id: user.id).pluck(:application_id))
  end

  def update
    user_application = UserApplication.find(params[:id])
    user_application.update(user_application_params)
    head :ok
  end

  def destroy
    user_application = UserApplication.find(params[:id])
    user_application.destroy
    redirect_to root_path
  end

  private
    def user_application_params
      params.require(:user_application).permit(:position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_applications_helper.rb
module UserApplicationsHelper
end

app/views/bulk_user_applications/_modal_form.html.erb
<dialog
  class="p-0 absolute bg-gray-100 rounded-lg open:backdrop:bg-gray-400 open:backdrop:opacity-75"
  data-modal-target="modal"
>
  <div class="p-6 min-w-[15rem] sm:min-w-[20rem] text-center">
    <button
      class="p-1 absolute top-2 right-2 pointer hover:bg-gray-300 rounded-lg transition duration-150"
      data-action="modal#close"
    >
      <%= render 'shared/x-icon' %>
    </button>
    <h2 class="font-semibold">Add Applications</h2>
    <% if @available_applications.count > 0 %>
      <%= form_with url: bulk_user_applications_path, data: { modal_target: 'form' } do |f| %>
        <div class="mt-4">
          <%= f.collection_check_boxes(:application_ids, @available_applications, :id, :name) do |item| %>
            <div class="flex items-center justify-between mt-4">
              <%= item.label %>
              <%= item.check_box class: "w-5 h-5 text-blue-600 border-gray-300 rounded focus:ring-blue-500 focus:ring-2 cursor-pointer" %>
            </div>
          <% end %>
        </div>
        <div class="actions mt-4">
          <%= f.submit "Submit", class: "bg-blue-300 hover:bg-blue-400 transition duration-150 rounded-lg py-2 px-4 cursor-pointer" %>
        </div>
      <% end %>
    <% else %>
      <p class="mt-10">
        No more applications available
      </p>
      <div class="mt-10">
        <button
          class="bg-blue-300 hover:bg-blue-400 transition duration-150 rounded-lg py-2 px-4 cursor-pointer"
          data-action="modal#close"
        >
          Close
        </button>
      </div>
    <% end %>
  </div>
</dialog>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApplicationHomepage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <header class="bg-gray-300">
      <nav class="flex items-center justify-end h-10 px-6 lg:px-8" aria-label="Global">
        <% if user_signed_in? %>
          <div data-controller="modal">
            <button class="flex items-center border-gray-300 border-b-2 hover:border-red-500 py-[.45rem]" data-action="modal#open">
              <%= render 'shared/plus-icon' %>
              Add App
            </button>
            <%= render 'bulk_user_applications/modal_form' %>
          </div>

          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'py-[.45rem] ml-6 border-b-2 border-gray-300 hover:border-red-500' %>
        <% else %>
          <%= button_to "Log In", new_user_session_path, method: :get, class: 'py-[.45rem] ml-6 border-b-2 border-gray-200 hover:border-red-500' %>
        <% end %>
      </nav>
    </header>

    <% if flash.count > 0 %>
      <div
        id="flash"
        data-controller="flash"
        class="mb-2 transition ease-in-out duration-150 text-center absolute w-full"
      >
        <% flash.each do |type, message| %>
          <div class="p-2 <%= type %>">
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>

    <main class="container mx-auto mt-16 px-5 flex flex-col items-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_boxes-icon.html.erb
<svg 
  xmlns="http://www.w3.org/2000/svg" 
  fill="none" 
  viewBox="0 0 24 24" 
  stroke-width="1.5" 
  stroke="currentColor" 
  class="w-6 h-6"
>
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z" />
</svg>

app/views/shared/_plus-icon.html.erb
<svg
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  viewBox="0 0 24 24"
  stroke-width="1.5"
  stroke="currentColor"
  class="w-4 h-4"
>
  <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
</svg>

app/views/shared/_x-icon.html.erb
<svg 
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  viewBox="0 0 24 24"
  stroke-width="1.5"
  stroke="currentColor"
  class="w-6 h-6"
>
  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
</svg>

app/views/user_applications/index.html.erb
<div
  class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 w-full"
  data-controller="sortable"
  data-sortable-animation-value="150"
  data-sortable-handle-value=".handle"
  data-sortable-resource-name-value="user_application"
>
  <% @user_applications.each do |user_app| %>
    <div
      class="min-h-[12rem] m-2 bg-gray-300 hover:bg-gray-400 rounded-lg"
      data-sortable-update-url="<%= user_application_path(user_app) %>"
    >
      <div class="<%= user_app.application.background_class %> h-full w-full rounded-lg relative transition-all duration-150">
        <div class="handle absolute top-2 left-2 pointer cursor-move">
          <%= render 'shared/boxes-icon' %>
        </div>


        <%= link_to user_application_path(user_app), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this application?" }, class: "p-1 absolute top-2 right-2 pointer hover:bg-gray-300 rounded-lg", title: "Remove application" do %>
            <%= render 'shared/x-icon' %>
        <% end %>

        <%= link_to user_app.application.link, target: "_blank", class: " p-2 h-full w-full flex flex-col items-center justify-center text-center transition duration-150" do %>
          <h2 class="text-2xl font-semibold">
            <%= user_app.application.name %>
          </h2>
          <p class="mt-4 text-sm">
            <%= user_app.application.description %>
          </p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>